#!/usr/bin/env python3
"""
Claude Code hook to prevent manual edits to Drizzle ORM migration files.

Drizzle migrations are auto-generated by drizzle-kit and should NEVER be
manually edited. This hook blocks Edit/Write operations on *.sql files
in the drizzle/ directory.

To modify the schema:
1. Edit packages/db/src/schema/*.ts
2. Run: cd packages/db && bun run db:generate
3. Run: cd packages/db && bun run db:migrate
"""
import json
import sys
import re

try:
    input_data = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # Allow on parse error (fail open)

tool_name = input_data.get("tool_name", "")
tool_input = input_data.get("tool_input", {})
file_path = tool_input.get("file_path", "")
command = tool_input.get("command", "")

BLOCKED_MSG = (
    "Migration files are auto-generated and must NOT be manually edited.\n\n"
    "To modify the database schema:\n"
    "  1. Edit packages/db/src/schema/*.ts\n"
    "  2. Run: cd packages/db && bun run db:generate\n"
    "  3. Run: cd packages/db && bun run db:migrate"
)

# Patterns matching migration file paths
migration_patterns = [
    r"packages/db/drizzle/.*\.sql",
    r"packages/db/drizzle/meta/.*\.json",
]

# Block Edit/Write operations targeting migration files
if tool_name in ["Edit", "Write"]:
    for pattern in migration_patterns:
        if re.search(pattern, file_path):
            print(
                f"BLOCKED: Cannot edit Drizzle migration file: {file_path}\n\n"
                + BLOCKED_MSG,
                file=sys.stderr,
            )
            sys.exit(2)

# Block Bash commands that write to migration files (sed, tee, cp, mv, echo/cat redirect)
if tool_name == "Bash" and command:
    for pattern in migration_patterns:
        if re.search(pattern, command):
            write_indicators = [
                r"\bsed\b.*-i",
                r"\btee\b",
                r"\bcp\b",
                r"\bmv\b",
                r">",
                r"\bdd\b",
                r"\bchmod\b",
                r"\brm\b",
                r"\btruncate\b",
            ]
            for indicator in write_indicators:
                if re.search(indicator, command):
                    print(
                        f"BLOCKED: Bash command would modify Drizzle migration files.\n\n"
                        + BLOCKED_MSG,
                        file=sys.stderr,
                    )
                    sys.exit(2)

sys.exit(0)
