workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Detent API:
        inputs:
            - location: https://backend.detent.sh/openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/detent/detent/detent-api
targets:
    detent:
        target: typescript
        source: Detent API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/detent/detent/detent-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
