/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Hint for which tool produced the output. Auto-detected if omitted.
 */
export const DetectedTool = {
  Eslint: "eslint",
  Vitest: "vitest",
  Typescript: "typescript",
  Cargo: "cargo",
  Golangci: "golangci",
} as const;
/**
 * Hint for which tool produced the output. Auto-detected if omitted.
 */
export type DetectedTool = ClosedEnum<typeof DetectedTool>;

/** @internal */
export const DetectedTool$outboundSchema: z.ZodMiniEnum<typeof DetectedTool> = z
  .enum(DetectedTool);
