/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DiagnosticLite = {
  /**
   * Error or warning message
   */
  message: string;
  /**
   * File path where the issue occurred
   */
  filePath?: string | undefined;
  /**
   * Line number (1-indexed)
   */
  line?: number | undefined;
  /**
   * Column number (1-indexed)
   */
  column?: number | undefined;
};

/** @internal */
export const DiagnosticLite$inboundSchema: z.ZodMiniType<
  DiagnosticLite,
  unknown
> = z.pipe(
  z.object({
    message: types.string(),
    file_path: types.optional(types.string()),
    line: types.optional(types.number()),
    column: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      file_path: "filePath",
    });
  })
);

export function diagnosticLiteFromJSON(
  jsonString: string
): SafeParseResult<DiagnosticLite, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiagnosticLite$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiagnosticLite' from JSON`
  );
}
