/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DiagnosticSummary,
  DiagnosticSummary$inboundSchema,
} from "./diagnostic-summary.js";
import { Diagnostic, Diagnostic$inboundSchema } from "./diagnostic.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DiagnosticsResponseFull = {
  /**
   * Response mode indicator (discriminator)
   */
  mode: "full";
  /**
   * Tool detected from output (null if unknown)
   */
  detectedTool: string | null;
  /**
   * Parsed diagnostics from the log
   */
  diagnostics: Array<Diagnostic>;
  /**
   * Aggregated counts
   */
  summary: DiagnosticSummary;
  /**
   * True if diagnostics were truncated (max 10,000)
   */
  truncated: boolean;
};

/** @internal */
export const DiagnosticsResponseFull$inboundSchema: z.ZodMiniType<
  DiagnosticsResponseFull,
  unknown
> = z.pipe(
  z.object({
    mode: types.literal("full"),
    detected_tool: types.nullable(types.string()),
    diagnostics: z.array(Diagnostic$inboundSchema),
    summary: DiagnosticSummary$inboundSchema,
    truncated: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "detected_tool": "detectedTool",
    });
  }),
);

export function diagnosticsResponseFullFromJSON(
  jsonString: string,
): SafeParseResult<DiagnosticsResponseFull, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiagnosticsResponseFull$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiagnosticsResponseFull' from JSON`,
  );
}
