/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Severity, Severity$inboundSchema } from "./severity.js";

export type Diagnostic = {
  /**
   * Error or warning message
   */
  message: string;
  /**
   * File path where the issue occurred
   */
  filePath?: string | undefined;
  /**
   * Line number (1-indexed)
   */
  line?: number | undefined;
  /**
   * Column number (1-indexed)
   */
  column?: number | undefined;
  /**
   * Issue severity level
   */
  severity: Severity;
  /**
   * Tool-specific rule identifier
   */
  ruleId?: string | undefined;
  /**
   * Stack trace if available (e.g., for test failures)
   */
  stackTrace?: string | undefined;
  /**
   * Suggested fixes from the tool
   */
  suggestions?: Array<string> | undefined;
  /**
   * Whether the tool can auto-fix this issue
   */
  fixable?: boolean | undefined;
};

/** @internal */
export const Diagnostic$inboundSchema: z.ZodMiniType<Diagnostic, unknown> = z
  .pipe(
    z.object({
      message: types.string(),
      file_path: types.optional(types.string()),
      line: types.optional(types.number()),
      column: types.optional(types.number()),
      severity: Severity$inboundSchema,
      rule_id: types.optional(types.string()),
      stack_trace: types.optional(types.string()),
      suggestions: types.optional(z.array(types.string())),
      fixable: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "file_path": "filePath",
        "rule_id": "ruleId",
        "stack_trace": "stackTrace",
      });
    }),
  );

export function diagnosticFromJSON(
  jsonString: string,
): SafeParseResult<Diagnostic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Diagnostic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Diagnostic' from JSON`,
  );
}
