/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import type * as discriminatedUnionTypes from "../types/discriminated-union.js";
import { discriminatedUnion } from "../types/discriminated-union.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import {
  type DiagnosticsResponseFull,
  DiagnosticsResponseFull$inboundSchema,
} from "./diagnostics-response-full.js";
import {
  type DiagnosticsResponseLite,
  DiagnosticsResponseLite$inboundSchema,
} from "./diagnostics-response-lite.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DiagnosticsResponse =
  | DiagnosticsResponseFull
  | DiagnosticsResponseLite
  | discriminatedUnionTypes.Unknown<"mode">;

/** @internal */
export const DiagnosticsResponse$inboundSchema: z.ZodMiniType<
  DiagnosticsResponse,
  unknown
> = discriminatedUnion("mode", {
  full: DiagnosticsResponseFull$inboundSchema,
  lite: DiagnosticsResponseLite$inboundSchema,
});

export function diagnosticsResponseFromJSON(
  jsonString: string
): SafeParseResult<DiagnosticsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiagnosticsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiagnosticsResponse' from JSON`
  );
}
