/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import type { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  type DiagnosticLite,
  DiagnosticLite$inboundSchema,
} from "./diagnostic-lite.js";
import type { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DiagnosticsResponseLite = {
  /**
   * Response mode indicator (discriminator)
   */
  mode: "lite";
  /**
   * Tool detected from output (null if unknown)
   */
  detectedTool: string | null;
  /**
   * Parsed diagnostics (minimal fields)
   */
  diagnostics: Array<DiagnosticLite>;
  /**
   * True if diagnostics were truncated (max 10,000)
   */
  truncated: boolean;
};

/** @internal */
export const DiagnosticsResponseLite$inboundSchema: z.ZodMiniType<
  DiagnosticsResponseLite,
  unknown
> = z.pipe(
  z.object({
    mode: types.literal("lite"),
    detected_tool: types.nullable(types.string()),
    diagnostics: z.array(DiagnosticLite$inboundSchema),
    truncated: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      detected_tool: "detectedTool",
    });
  })
);

export function diagnosticsResponseLiteFromJSON(
  jsonString: string
): SafeParseResult<DiagnosticsResponseLite, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiagnosticsResponseLite$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiagnosticsResponseLite' from JSON`
  );
}
