/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  type DetectedTool,
  DetectedTool$outboundSchema,
} from "./detected-tool.js";
import { type ModeEnum, ModeEnum$outboundSchema } from "./mode-enum.js";

export type DiagnosticsRequest = {
  /**
   * Raw CI/build log content to parse
   */
  content: string;
  /**
   * Hint for which tool produced the output. Auto-detected if omitted.
   */
  tool?: DetectedTool | undefined;
  /**
   * Response detail level. 'full' includes severity, ruleId, suggestions. 'lite' is minimal.
   */
  mode?: ModeEnum | undefined;
};

/** @internal */
export type DiagnosticsRequest$Outbound = {
  content: string;
  tool?: string | undefined;
  mode: string;
};

/** @internal */
export const DiagnosticsRequest$outboundSchema: z.ZodMiniType<
  DiagnosticsRequest$Outbound,
  DiagnosticsRequest
> = z.object({
  content: z.string(),
  tool: z.optional(DetectedTool$outboundSchema),
  mode: z._default(ModeEnum$outboundSchema, "full"),
});

export function diagnosticsRequestToJSON(
  diagnosticsRequest: DiagnosticsRequest
): string {
  return JSON.stringify(
    DiagnosticsRequest$outboundSchema.parse(diagnosticsRequest)
  );
}
