/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Aggregated counts
 */
export type DiagnosticSummary = {
  /**
   * Total number of diagnostics
   */
  total: number;
  /**
   * Number of errors
   */
  errors: number;
  /**
   * Number of warnings
   */
  warnings: number;
};

/** @internal */
export const DiagnosticSummary$inboundSchema: z.ZodMiniType<
  DiagnosticSummary,
  unknown
> = z.object({
  total: types.number(),
  errors: types.number(),
  warnings: types.number(),
});

export function diagnosticSummaryFromJSON(
  jsonString: string,
): SafeParseResult<DiagnosticSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DiagnosticSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DiagnosticSummary' from JSON`,
  );
}
