/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import type { ClosedEnum } from "../types/enums.js";

/**
 * Response detail level. 'full' includes severity, ruleId, suggestions. 'lite' is minimal.
 */
export const ModeEnum = {
  Full: "full",
  Lite: "lite",
} as const;
/**
 * Response detail level. 'full' includes severity, ruleId, suggestions. 'lite' is minimal.
 */
export type ModeEnum = ClosedEnum<typeof ModeEnum>;

/** @internal */
export const ModeEnum$outboundSchema: z.ZodMiniEnum<typeof ModeEnum> =
  z.enum(ModeEnum);
