/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type * as z from "zod/v4-mini";
import type { OpenEnum } from "../types/enums.js";
import * as openEnums from "../types/enums.js";

/**
 * Issue severity level
 */
export const Severity = {
  Error: "error",
  Warning: "warning",
} as const;
/**
 * Issue severity level
 */
export type Severity = OpenEnum<typeof Severity>;

/** @internal */
export const Severity$inboundSchema: z.ZodMiniType<Severity, unknown> =
  openEnums.inboundSchema(Severity);
