/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { diagnosticsPostV1Diagnostics } from "../funcs/diagnostics-post-v1-diagnostics.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Diagnostics extends ClientSDK {
  /**
   * Parse CI/build logs into structured diagnostics
   *
   * @remarks
   * Extracts structured error and warning information from raw CI/build log output.
   *
   * Supports auto-detection of common tools (ESLint, TypeScript, Vitest, Cargo, golangci-lint) or accepts a hint via the `tool` parameter.
   *
   * Returns parsed diagnostics with file locations, severity, and tool-specific metadata.
   *
   * **Note:** Sensitive data (API keys, tokens, credentials) detected in the output is automatically redacted for security.
   */
  async postV1Diagnostics(
    request: models.DiagnosticsRequest,
    options?: RequestOptions,
  ): Promise<models.DiagnosticsResponse> {
    return unwrapAsync(diagnosticsPostV1Diagnostics(
      this,
      request,
      options,
    ));
  }
}
