/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Diagnostics } from "./diagnostics.js";

export class Detent extends ClientSDK {
  private _diagnostics?: Diagnostics;
  get diagnostics(): Diagnostics {
    return (this._diagnostics ??= new Diagnostics(this._options));
  }
}
