/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";

dotenv.config();

/**
 * Example usage of the @detent/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx diagnosticsPostV1Diagnostics.example.ts
 */

import { Detent } from "@detent/sdk";

const detent = new Detent();

async function main() {
  const result = await detent.diagnostics.postV1Diagnostics({
    content: "src/app.ts:10:5 - error TS2304: Cannot find name 'foo'",
  });

  console.log(result);
}

main().catch(console.error);
