/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { DetentError } from "./detent-error.js";

export type RateLimitErrorData = {
  /**
   * Rate limit error message
   */
  error: string;
  /**
   * Unix timestamp when the rate limit resets
   */
  retryAfter: number;
};

export class RateLimitError extends DetentError {
  /**
   * Rate limit error message
   */
  error: string;
  /**
   * Unix timestamp when the rate limit resets
   */
  retryAfter: number;

  /** The original data that was passed to this error instance. */
  data$: RateLimitErrorData;

  constructor(
    err: RateLimitErrorData,
    httpMeta: { response: Response; request: Request; body: string }
  ) {
    const message =
      "message" in err && typeof err.message === "string"
        ? err.message
        : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.retryAfter = err.retryAfter;

    this.name = "RateLimitError";
  }
}

/** @internal */
export const RateLimitError$inboundSchema: z.ZodMiniType<
  RateLimitError,
  unknown
> = z.pipe(
  z.object({
    error: types.string(),
    retryAfter: types.number(),
    request$: z.custom<Request>((x) => x instanceof Request),
    response$: z.custom<Response>((x) => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new RateLimitError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  })
);
