// biome-ignore-all lint/performance/noBarrelFile: This is the package entry point

export { type ExtractionOptions, extractIssueDiagnostics } from "./extract.js";
export {
  buildClusterKey,
  createIssueDiagnosticDraft,
  dedupeIssueDiagnostics,
  issueCategoryRank,
  normalizeSourceKinds,
  rankIssueDiagnostics,
  sanitizeIssueObservationContext,
  sanitizeIssueObservationMemory,
  sanitizeRelatedIssueMemory,
  scrubUnknown,
} from "./normalize.js";
export {
  type CompactResult,
  compactCiOutput,
  type LogSegment,
  type PrepareResult,
  prepareForPrompt,
  sanitizeForPrompt,
  type TruncateResult,
  truncateContent,
} from "./preprocess.js";
export {
  buildIssueExtractionPrompt,
  ISSUE_EXTRACTION_SYSTEM_PROMPT,
} from "./prompt.js";
export {
  type IssueCategory,
  IssueCategorySchema,
  type IssueDiagnosticDraft,
  IssueDiagnosticDraftSchema,
  type IssueDiagnosticSeed,
  IssueDiagnosticSeedSchema,
  IssueDiagnosticSeveritySchema,
  type IssueEnvironment,
  IssueEnvironmentSchema,
  type IssueExtractionMetrics,
  IssueExtractionMetricsSchema,
  type IssueExtractionResult,
  IssueExtractionResultSchema,
  type IssueExtractionUsage,
  IssueExtractionUsageSchema,
  type IssueObservationContext,
  IssueObservationContextSchema,
  type IssueObservationDraft,
  IssueObservationDraftSchema,
  type IssueObservationMemory,
  IssueObservationMemorySchema,
  type IssuePlan,
  IssuePlanSchema,
  type IssueSeverity,
  IssueSeveritySchema,
  type IssueSnapshotDraft,
  IssueSnapshotDraftSchema,
  type IssueStatus,
  IssueStatusSchema,
  issueCategoryValues,
  issueDiagnosticSeverityValues,
  issueEnvironmentValues,
  issueSeverityValues,
  issueStatusValues,
  LogSegmentSchema,
  type ObservationSourceKind,
  ObservationSourceKindSchema,
  observationSourceKindValues,
  type RelatedIssueMemory,
  RelatedIssueMemorySchema,
} from "./schema.js";
export {
  generateIssueSnapshot,
  type IssueSynthesisInput,
} from "./snapshot.js";
